name: Publish JSON Schemas
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Publish
    environment: Production
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Set-up s5cmd
        uses: peak/action-setup-s5cmd@bde462e7399c68b4a9b05549d90b0e7d5c95e60f
        with:
          version: v2.3.0

      - name: Checkout
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 25

      - name: Install dependencies
        run: pnpm install

      - name: Generate schemas
        run: pnpm generate

      - name: Publish npm package
        # Git checks were disabled to allow publishing from a detached HEAD state on releases
        run: pnpm build && pnpm publish --provenance --no-git-checks

      - name: Upload schemas
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          s5cmd --endpoint-url ${{ vars.AWS_ENDPOINT_URL }} sync --delete 'public/v*' 's3://hackfed-schemas/'
